apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-dep
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-ctr
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000

------------------

SERVICE

apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - port: 3000
    targetPort: 3000




