name: random-workflow
on: 
   push
env:
  MARKET: "COSTCO"
  NUMBER: 7
jobs:
    hello-job:
         runs-on: ubuntu-latest
         steps:
           - name: Print Hello
             run: echo "Hello"
           - name: Printing Variables
             run: |
              echo "$MARKET"
              echo "$NUMBER"
              
         
    # runners --> windows, macos , ubuntu
  
