name: massage
on: [push]
jobs:
  head-massage:
    runs-on: ubuntu-lastest
    steps:
      - name: Oiling
        run: echo "Ejike get ready for oiling in thailand"
      - name: shaking head
        run: echo "Shake the head and relax"
  body-massage:
     runs-on: ubuntu-latest
     steps:
       - name: Oiling
         run: echo "Ejike get ready for oiling in thailand BODY TIME!!"
       - name: Back massage
         run: echo "Just relax and feel the nerves"
       - name: Feet massage
         run: echo "Droping oil on feets so that your ankle nerves get repaired"
         
    # runners --> windows, macos , ubuntu
  
