name: random-workflow
on: 
   push
env:
  MARKET: "COSTCO"
  NUMBER: 7
jobs:
    hello-job:
         runs-on: ubuntu-latest
         steps:
          - name: Download the code
          - uses: actions/checkout@v5
          - name: Let's check if we have downloaded the code or not
            run: ls 
              
         
    # runners --> windows, macos , ubuntu
  
